# Copyright (C) 2024 Innovate for Vegas Foundation
# 
# This file is part of doc-agile-for-volunteers.
# 
# doc-agile-for-volunteers is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# doc-agile-for-volunteers is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with doc-agile-for-volunteers.  If not, see <https://www.gnu.org/licenses/>.

blank_issues_enabled: false
contact_links:
  - name: "Discussion: Agile for Volunteers Iteration"
    url: https://github.com/ORG-OR-USER/BE-PROJECT-NAME/discussions/categories/iteration
    about: GitHub Discussion about a current Initiative Iteration for this Component Project
  - name: "Discussion: Back End Implementation Design"
    url: https://github.com/ORG-OR-USER/BE-PROJECT-NAME/discussions/categories/design
    about: GitHub Discussion pondering this Back End Implementation tuning and ideas
  - name: "Discussion: External Defect"
    url: https://github.com/ORG-OR-USER/BE-PROJECT-NAME/discussions/categories/external-defect
    about: GitHub Discussion of externally-discovered defects with project team
  - name: "Discussion: This Repository"
    url: https://github.com/ORG-OR-USER/BE-PROJECT-NAME/discussions/categories/repo
    about: GitHub Discussion about this Component Project repository
  - name: "Discussion: INITIATIVE-NAME Initiative Feature Request"
    url: https://github.com/ORG-OR-USER/OV-PROJECT-NAME/discussions/categories/feature-request
    about: GitHub Discussion for pondering focused new INITIATIVE-NAME Features
  - name: "Discussion: INITIATIVE-NAME Initiative Theme Request"
    url: https://github.com/ORG-OR-USER/OV-PROJECT-NAME/discussions/categories/theme-request
    about: GitHub Discussion for pondering broad new INITIATIVE-NAME Themes
  - name: "EXTERNAL example"
    url: https://example.com
    about: Visit here for general discussion, future notions, etc
